name: Auto-format
on: [push, pull_request]
jobs:
  apply-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Clone git repo
        uses: actions/checkout@v2

      - id: format
        uses: xmos/xaction_format@v1.0
        with:
          file-extensions:  |
            py
          exclude-dirs:
          python-style: black
          token: ${{ secrets.GITHUB_TOKEN }}
